### ISSUE TITLE
Artemis For PS2 - Upload current ps2rd source

### ISSUE THREAD

**Issue by LBGSHI** [GameHackingDotOrg/Project_Artemis#7]
For misfire.

**Comment by mlafeldt** [comment]
PS2rd lives at https://github.com/mlafeldt/ps2rd You can fork it to this org if you want.

What's the goal of this issue anyway?

**Comment by LBGSHI** [comment]
Yep, looks like dnawrkshp beat me to it, heh:
https://github.com/GameHackingDotOrg/ps2rd

But, thanks. I wasn't sure if you still had ps2rd publicly available. I was just typing off a brief list of tasks, off the cuff, to get the ball rolling, and if ps2rd was only available in some backup or archive somewhere, I wanted to get it back online. It's definitely a core component of Artemis for PS2.

Anyway, we've re-organized (actually, dnawrkshp has) this org into separate repos per sub-project, so this repo is about to be nuked.
